{% set name = "flask_simplelogin" %}
{% set version = "0.0.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/flask_simplelogin-{{ version }}.tar.gz
  sha256: 338d6d54cc00a7df043979e3a362a05fef427855a57ad609707ef8b4eec91b9d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - click
    - flask >=0.12
    - flask-wtf
    - python >={{ python_min }}

test:
  imports:
    - example
    - flask_simplelogin
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cuducos/flask_simplelogin
  summary: Flask Simple Login - Login Extension for Flask
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
